language: python
python:
  - "3.7.3"
install:
  - pip3 install homeassistant
  - pip3 install colorlog
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
