##############################################################
## Binary Sensor  ##
##############################################################

##########################################################
## octoprint
##########################################################

- platform: octoprint
  monitored_conditions:
    - Printing
    - Printing Error
    
##########################################################
## Occupancy Templates
##########################################################

- platform: template
  sensors:
    living_occupancy_on:
      friendly_name: Living Occupancy
      value_template: "{{ states.input_boolean.living_occupancy.state == 'on' }}"
      device_class: motion

- platform: template
  sensors:
    garage_occupancy_on:
      friendly_name: Garage Occupancy
      value_template: "{{ states.input_boolean.garage_occupancy.state == 'on' }}"
      device_class: motion

- platform: template
  sensors:
    chalkboard_occupancy_on:
      friendly_name: Chalkboard Occupancy
      value_template: "{{ states.input_boolean.chalkboard_occupancy.state == 'on' }}"
      device_class: motion

- platform: template
  sensors:
    shop_occupancy_on:
      friendly_name: Shop Occupancy
      value_template: "{{ states.input_boolean.shop_occupancy.state == 'on' }}"
      device_class: motion

- platform: template
  sensors:
    office_occupancy_on:
      friendly_name: Office Occupancy
      value_template: "{{ states.input_boolean.office_occupancy.state == 'on' }}"
      device_class: motion

- platform: template
  sensors:
    baby_occupancy_on:
      friendly_name: Baby Occupancy
      value_template: "{{ states.input_boolean.baby_occupancy.state == 'on' }}"
      device_class: motion

- platform: ping
  host: !secret unifi_usg_host
  name: UniFi USG

- platform: ping
  host: !secret unifi_sw8_host
  name: UniFi SW8 60w

- platform: ping
  host: !secret unifi_apacpro_loft_host
  name: UniFi AP Loft

- platform: ping
  host: !secret unifi_apacpro_living_host
  name: UniFi AP Living

##########################################################
## Network Devices
##########################################################

- platform: ping
  host: !secret unifi_usg_host
  name: USG GW

- platform: ping
  host: !secret unifi_sw8_host
  name: SW8 60w

- platform: ping
  host: !secret unifi_apacpro_loft_host
  name: AP Loft

- platform: ping
  host: !secret unifi_apacpro_living_host
  name: AP Living

- platform: ping
  host: !secret pihole_host
  name: PiHole

- platform: ping
  host: !secret nas2_host
  name: NAS2

- platform: ping
  host: !secret amcrest_garage_host
  name: Garage cam

- platform: ping
  host: !secret amcrest_living_host
  name: Living cam

- platform: ping
  host: !secret amcrest_chalkboard_host
  name: Chalkboard cam

- platform: ping
  host: !secret amcrest_shop_host
  name: Shop cam

- platform: ping
  host: !secret harmony_hub_host
  name: Harmony living

- platform: ping
  host: !secret master_harmony_hub_host
  name: Harmony master

- platform: ping
  host: !secret ring_pro_host
  name: Ring pro

