##############################################################
## Camera  ##
##############################################################

- platform: mjpeg
  name: Baby Camera
  mjpeg_url: !secret baby_cam_mjpeg
  username: !secret baby_camera_user
  password: !secret baby_camera_pass

- platform: mjpeg
  name: OctoPrint
  still_image_url: http://REDACTED35/webcam/?action=snapshot
  mjpeg_url: http://REDACTED35/webcam/?action=stream
