#################################################################
## Home Assistant
#################################################################
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  customize: !include customize.yaml
  time_zone: !secret homeassistant_timezone
  allowlist_external_dirs:
    - /shared
    - /config

api:
frontend:
  themes: !include_dir_merge_named themes
updater:
  reporting: no
  include_used_components: true
sun:
#ios:
map:
config:
discovery:
  ignore:
#    - sonos
    - netgear_router
    - harmony
    - google_cast
    - philips_hue
    - yeelight
    - denonavr
#conversation:
logger: !include logger.yaml

logbook: !include logbook.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity/battery-entity.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/text-divider-row/text-divider-row.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/air-visual-card/air-visual-card.js
      type: module

shell_command:
  docker_image_prune: "ssh -i /shared/id_rsa -oStrictHostKeyChecking=no ubuntu@REDACTED54 'docker image prune -af'"

system_health:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

#################################################################
## Components
#################################################################

airvisual:
  api_key: !secret airvisual_api
  geographies:
      latitude: !secret homeassistant_latitude
      longitude: !secret homeassistant_longitude

amcrest:
  - host: !secret amcrest_living_host
    name: Living Room
    username: !secret amcrest_user
    password: !secret amcrest_pass
    binary_sensors:
      - motion_detected
    stream_source: rtsp

  - host: !secret amcrest_garage_host
    name: Garage
    username: !secret amcrest_user
    password: !secret amcrest_pass
    binary_sensors:
      - motion_detected
    stream_source: rtsp

  - host: !secret amcrest_chalkboard_host
    name: Chalkboard Room
    username: !secret amcrest_user
    password: !secret amcrest_pass
    binary_sensors:
      - motion_detected
    stream_source: rtsp

  - host: !secret amcrest_shop_host
    name: Shop
    username: !secret amcrest_user
    password: !secret amcrest_pass
    binary_sensors:
      - motion_detected
    stream_source: rtsp

breaking_changes:

ffmpeg:

life360:
  driving_speed: 10
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  warning_threshold: 2
  error_threshold: 3

monitor_docker:
  - name: docker-ub1
    containers:
      - homeassistant

nexia:
  username: !secret nexia_username
  password: !secret nexia_password

octoprint:
  host: !secret octopi_host
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1

#pi_hole:
#  - host: !secret pihole_host
#    ssl: true
#    verify_ssl: false
#    api_key: !secret pi_hole_api_key

ring:
  username: !secret ring_username
  password: !secret ring_password

tts:
  - platform: google_translate
    cache: true
    time_memory: 300

#tuya:
#  username: !secret tuya_username
#  password: !secret tuya_password
#  country_code: 1
#  platform: smart_life

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

wemo:
  static:
    - !secret wemo_insight_host

yeelight:
  devices:
    !secret media_center_l_strip_host:
      name: Media Center L Strip
      model: strip1
    !secret media_center_r_strip_host:
      name: Media Center R Strip
      model: strip1

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
history: !include history.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
light: !include light.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml
remote: !include remote.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
zone: !include zones.yaml
