#################################################################
## Home Assistant
#################################################################
homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  currency: USD
  country: US
  customize: !include customize.yaml
  time_zone: !secret homeassistant_timezone
  external_url: "https://ha.useroneREDACTED.com"
  internal_url: "http://REDACTED:8123"
  allowlist_external_dirs:
    - /shared
    - /config
  allowlist_external_urls:
    - "https://ha.useroneREDACTED.com/api/frigate/notifications/"

api:
frontend:
  themes: !include_dir_merge_named themes
sun:
map:
config:
logger: !include logger.yaml

logbook: !include logbook.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity/battery-entity.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/text-divider-row/text-divider-row.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/air-visual-card/air-visual-card.js
      type: module
    - url: /hacsfiles/entity-attributes-card/entity-attributes-card.js?=v2
      type: module
    - url: /hacsfiles/threedy/threedy-card.js
      type: module

rest_command: 
  office_air_purifier:
    url: https://developer-api.govee.com/v1/appliance/devices/control
    method: PUT
    headers:
        Content-Type: application/json
        Govee-API-Key: !secret govee_api_key
    content_type:  'application/json; charset=utf-8'
    payload: '{"device": "{{ device }}","model": "{{ model }}","cmd": {"name": "{{ cmd_name }}","value": "{{ cmd_value }}"}}'
    verify_ssl: true

system_health:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24

#################################################################
## Components
#################################################################

alexa:
  smart_home:
    filter:
      include_entities:
        - switch.pentair_REDACTED_spa
        - light.pentair_REDACTED_lights
        - switch.pentair_REDACTED_spillway
        - sensor.pentair_REDACTED_pool_temperatur
        - switch.media_center_shield
        - switch.media_center_switch
        - switch.media_center_xbox
    entity_config:
      switch.pentair_REDACTED_spa:
        name: "Spa"
        description: "The spa"
      light.pentair_REDACTED_lights:
        name: "Pool light"
        description: "Pool light"
      switch.pentair_REDACTED_spillway:
        name: "Spillway"
        description: "Spillway"
      sensor.pentair_REDACTED_pool_temperature:
        name: "Pool"
        description: "Pool water temperature"
      switch.media_center_shield:
        name: "Shield"
        description: "Downstairs nvidia shield harmony activity"
      switch.media_center_switch:
        name: "Switch"
        description: "Downstairs nin switch harmony activity"
      switch.media_center_xbox:
        name: "Xbox"
        description: "Downstairs xbox harmony activity"

fan:
  platform: template
  fans:
    office_air_purifier:
      friendly_name: "Office Air Purifier"
      value_template: "{{ states('input_boolean.office_purifier_state') }}"
      preset_mode_template: "{{ states('input_select.office_air_purifier_mode') }}"
      turn_on:
        service: script.office_air_purifier_on
      turn_off:
        service: script.office_air_purifier_off
      set_preset_mode:
        service: script.office_air_purifier_mode
        data:
          office_purifier_mode: >
            {% set mapper = {'Sleep' : 16, 'Low': 1, 'Medium': 2, 'High': 3} %}
            {{ mapper[preset_mode] }}
      speed_count: 4
      preset_modes:
        - 'Low'
        - 'Medium'
        - 'High'
        - 'Sleep'

ffmpeg:

monitor_docker:
  - name: docker1
    url: tcp://REDACTED54:2375
  - name: docker2
    url: tcp://REDACTED53:2375
    containers:
      - unifi-controller
  - name: docker3
    url: tcp://REDACTED:2375
    containers:
      - homeassistant

tts:
  - platform: google_translate
    cache: true
    time_memory: 300
    #base_url: http://REDACTED:8123
    
sonos:
  media_player:
    hosts:
      - REDACTED
      - REDACTED
      - REDACTED
      - REDACTED

yeelight:
  devices:
    !secret media_center_l_strip_host:
      name: Media Center L Strip
      model: strip1
    !secret media_center_r_strip_host:
      name: Media Center R Strip
      model: strip1

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensor.yaml
command_line: !include command_line.yaml
group: !include groups.yaml
history:
input_boolean: !include input_boolean.yaml
input_button: !include input_button.yaml
input_datetime: !include input_datetime.yaml
input_select: !include input_select.yaml
light: !include light.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
shell_command: !include shell_command.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
zone: !include zones.yaml
