##############################################################
## Light  ##
##############################################################

##########################################################
## Light Groups
##########################################################

- platform: group
  name: Media Accents
  entities:
    - light.media_center_l_strip
    - light.media_center_r_strip
    
      ##########################################################
      ## Kitchen cabinet underlights
      ##########################################################

- platform: flux_led
  devices:
    REDACTED83:
      name: kitchen_cabinet_lights
