##############################################################
## Light  ##
##############################################################

##########################################################
## Light Groups
##########################################################

- platform: group
  name: Media Accents
  entities:
    - light.media_center_l_strip
    - light.media_center_r_strip

- platform: group
  name: Exterior Lights
  entities:
    - light.jasco_products_14294_in_wall_smart_dimmer_level
    - light.jasco_products_14294_in_wall_smart_dimmer_level_2
    
##########################################################
## Kitchen cabinet underlights
##########################################################

- platform: flux_led
  devices:
    REDACTED83:
      name: kitchen_cabinet_lights
