##############################################################
## Light  ##
##############################################################

##########################################################
## Light Groups
##########################################################

- platform: group
  name: Media Accents
  entities:
    - light.media_center_l_strip
    - light.media_center_r_strip

- platform: group
  name: Exterior Lights
  entities:
    - light.front_porch
    - light.back_porch
    - light.side
