views:
  - !include /config/lovelace/00_overview.yaml
  - !include /config/lovelace/01_climate.yaml
  - !include /config/lovelace/02_server.yaml
  - !include /config/lovelace/03_sensors.yaml
  - !include /config/lovelace/04_automation.yaml
