##############################################################
## Light  ##
##############################################################

##########################################################
## Light Groups
##########################################################

- platform: group
  name: front porch group
  entities:
    - light.front_bulb
    - light.front_porch

- platform: group
  name: side porch group
  entities:
    - light.side_bulb
    - light.side

- platform: group
  name: Media Accents
  entities:
    - light.media_center_l_strip
    - light.media_center_r_strip

- platform: group
  name: exterior porch lights
  entities:
    - light.front_porch_group
    - light.side_porch_group

- platform: group
  name: exterior porch bulbs
  entities:
    - light.front_bulb
    - light.side_bulb

- platform: group
  name: Media Center Lamp Bulbs
  entities:
    - light.media_lamp_bulb1
    - light.media_lamp_bulb2
    - light.media_lamp_bulb3

- platform: group
  name: back porch group
  entities:
    - light.back_bulb
    - light.back_porch

- platform: group
  name: exterior flood lights
  entities:
    - light.front_flood_lights
    - light.smart_flood_lights