##################################################################
## Holiday Automations
##################################################################

  ##########################################################
  ## Halloween - Lighting via calendar
  ##########################################################

- alias: Holiday - Enable Halloween Lighting
  trigger:
    - platform: state
      entity_id: sensor.holidays_calendar
      to: 'Halloween'
      for:
        hours: 48
        minutes: 0
        seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.exterior_holiday
      state: 'On'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Halloween'

  ##########################################################
  ## Halloween - Lighting via input_select
  ##########################################################

- alias: Holiday - Halloween Lighting Front
  trigger:
    - platform: state
      entity_id: input_select.holiday
      to: 'Halloween'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: light.front_flood_lights
        state: 'on'
  action:
    #turn floods to purple
    - service: light.turn_on
      data:
        entity_id: light.exterior_flood_lights
        rgb_color:
          - 183
          - 47
          - 255
        brightness_pct: 100
    #turn on front group and purple
    - service: light.turn_on
      data:
        entity_id: light.front_porch_group
        rgb_color:
          - 183
          - 47
          - 255
        brightness_pct: 100
    #turn on side group and purple
    - service: light.turn_on
      data:
        entity_id: light.side_porch_group
        rgb_color:
          - 183
          - 47
          - 255
        brightness_pct: 100
    #turn on spotlights red
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight2
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100

  ##########################################################
  ## Halloween - Change colors
  ##########################################################

- alias: Holiday - Halloween Lighting Front Floods Switch Color
  trigger:
    - platform: state
      entity_id: light.front_flood_lights
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Halloween'
  action:
    #turn front floods to purple
    - service: light.turn_on
      data:
        entity_id: light.front_flood_lights
        rgb_color:
          - 183
          - 47
          - 255
        brightness_pct: 100
    #turn on bedroom eye lights
    - service: switch.turn_on
      data:
        entity_id: switch.plug_s31_userthree
    - service: switch.turn_on
      data:
        entity_id: switch.plug_s31_userfour

- alias: Holiday - Halloween Lighting Front Bulb Switch Color
  trigger:
    - platform: state
      entity_id: light.front_bulb
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Halloween'
  action:
    #turn front bulb to purple
    - service: light.turn_on
      data:
        entity_id: light.front_porch_group
        rgb_color:
          - 183
          - 47
          - 255
        brightness_pct: 100
    #turn on bedroom eye lights
    - service: switch.turn_on
      data:
        entity_id: switch.plug_s31_userthree
    - service: switch.turn_on
      data:
        entity_id: switch.plug_s31_userfour

- alias: Holiday - Halloween Lighting Side Bulb Switch Color
  trigger:
    - platform: state
      entity_id: light.side_bulb
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Halloween'
  action:
    #turn front bulb to red
    - service: light.turn_on
      data:
        entity_id: light.side_porch_group
        rgb_color:
          - 183
          - 47
          - 255
        brightness_pct: 100

- alias: Holiday - Halloween Lighting Pool Switch Color
  trigger:
    - platform: state
      entity_id: light.lights
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Halloween'
  action:
    #turn front pool to red
    - service: light.turn_on
      entity_id: light.lights
      data:
        effect: Red

- alias: Holiday - Halloween Lighting Front Splotlight Switch Color
  trigger:
    - platform: state
      entity_id: light.front_spotlight
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Halloween'
  action:
    #turn on spotlights red
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100
    - delay: '00:05:00'
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100

- alias: Holiday - Halloween Lighting Front Splotlight2 Switch Color
  trigger:
    - platform: state
      entity_id: light.front_spotlight2
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Halloween'
  action:
    #turn on spotlights red
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight2
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100
    - delay: '00:05:00'
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight2
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100

  ##########################################################
  ## Halloween - Turn off window light switches
  ##########################################################

- alias: halloween window light switches off at sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_off_sunrise
      state: 'off'
  action:
    #turn off bedroom eye lights
    - service: switch.turn_off
      data:
        entity_id: switch.plug_s31_userthree
    - service: switch.turn_off
      data:
        entity_id: switch.plug_s31_userfour

  ##########################################################
  ## Christmas - Lighting via calendar
  ##########################################################

- alias: Holiday - Enable Christmas Lighting
  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.holidays_calendar
        state: 'Christmas Eve'
      - condition: state
        entity_id: sensor.holidays_calendar
        state: 'Christmas Day'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Christmas'

  ##########################################################
  ## Christmas - Lighting via input_select
  ##########################################################

- alias: Holiday - Christmas Lighting Front Flood
  trigger:
    - platform: state
      entity_id: input_select.holiday
      to: 'Christmas'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: light.front_flood_lights
        state: 'on'
  action:
    #turn floods to red
    - service: light.turn_on
      data:
        entity_id: light.exterior_flood_lights
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100
    #turn on front group and red
    - service: light.turn_on
      data:
        entity_id: light.front_porch_group
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100
    #turn on side group and red
    - service: light.turn_on
      data:
        entity_id: light.side_porch_group
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100
    #turn on spotlights green
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight
        rgb_color:
          - 0
          - 255
          - 0
        brightness_pct: 100
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight2
        rgb_color:
          - 0
          - 255
          - 0
        brightness_pct: 100
    #turn on outdoor christmas leds
    - service: switch.turn_on
      data:
        entity_id: switch.spare_downstairs_switch_3

  ##########################################################
  ## Christmas - Change colors
  ##########################################################

- alias: Holiday - Christmas Lighting Front Floods Switch Color
  trigger:
    - platform: state
      entity_id: light.front_flood_lights
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Christmas'
  action:
    #turn front floods to red
    - service: light.turn_on
      data:
        entity_id: light.front_flood_lights
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100
    #turn on outdoor christmas leds
    - service: switch.turn_on
      data:
        entity_id: switch.spare_downstairs_switch_3

- alias: Holiday - Christmas Lighting Front Bulb Switch Color
  trigger:
    - platform: state
      entity_id: light.front_bulb
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Christmas'
  action:
    #turn front bulb to red
    - service: light.turn_on
      data:
        entity_id: light.front_porch_group
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100

- alias: Holiday - Christmas Lighting Side Bulb Switch Color
  trigger:
    - platform: state
      entity_id: light.side_bulb
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Christmas'
  action:
    #turn front bulb to red
    - service: light.turn_on
      data:
        entity_id: light.side_porch_group
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 100

- alias: Holiday - Christmas Lighting Pool Switch Color
  trigger:
    - platform: state
      entity_id: light.lights
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Christmas'
  action:
    #turn front pool to green
    - service: light.turn_on
      entity_id: light.lights
      data:
        effect: Green

- alias: Holiday - Christmas Lighting Front Splotlight Switch Color
  trigger:
    - platform: state
      entity_id: light.front_spotlight
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Christmas'
  action:
    #turn on spotlights green
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight
        rgb_color:
          - 0
          - 255
          - 0
        brightness_pct: 100
    - delay: '00:05:00'
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight
        rgb_color:
          - 0
          - 255
          - 0
        brightness_pct: 100

- alias: Holiday - Christmas Lighting Front Splotlight2 Switch Color
  trigger:
    - platform: state
      entity_id: light.front_spotlight2
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.exterior_holiday
        state: 'on'
      - condition: state
        entity_id: input_select.holiday
        state: 'Christmas'
  action:
    #turn on spotlights green
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight2
        rgb_color:
          - 0
          - 255
          - 0
        brightness_pct: 100
    - delay: '00:05:00'
    - service: light.turn_on
      data:
        entity_id: light.front_spotlight2
        rgb_color:
          - 0
          - 255
          - 0
        brightness_pct: 100

  ##########################################################
  ## Christmas - Turn off christmas leds
  ##########################################################

- alias: Christmas turn off leds
  trigger:
    - platform: sun
      event: sunrise
      offset: "-00:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_off_sunrise
      state: 'off'
  action:
    #turn off outdoor christmas leds
    - service: switch.turn_off
      data:
        entity_id: switch.spare_downstairs_switch_3

##########################################################
## thanksgiving/christmas
##########################################################

- alias: "dept56 - dickens village"
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_interior_on_sunset
        state: "off"
      - condition: state
        entity_id: input_boolean.interior_holiday
        state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.plug_s31_village

- alias: "dept56 - dickens village turn off"
  trigger:
    - platform: state
      entity_id: switch.cactus
      from: "on"
      to: "off"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_interior_on_sunset
        state: "off"
      - condition: state
        entity_id: input_boolean.interior_holiday
        state: "on"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.plug_s31_village
