#################################################################
## Known house guest
#################################################################

        ##########################################################
        ## Set House Cleaning Mode On thursdays
        ##########################################################

- alias: guest set house cleaning mode on at 10am thursdays
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    - condition: time
      weekday:
        - thu
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.house_cleaning_mode

- alias: guest set house cleaning mode off after 3 hours
  trigger:
    - platform: time
      at: '13:00:00'
  condition:
    - condition: time
      weekday:
        - thu
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.house_cleaning_mode
