#################################################################
## Lighting Automations
#################################################################

##########################################################
## Interior - Kitchen Cabinets
##########################################################

- alias: "light sunset transition kitchen cabinets"
  trigger:
    - platform: time_pattern
      minutes: "/1"
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: time
        after: "15:00:00"
        before: "21:00:00"
      - condition: numeric_state
        entity_id: sensor.sun_elevation
        above: 0
        below: 9
      - condition: state
        entity_id: input_boolean.disable_interior_on_sunset
        state: "off"
      - condition: or
        conditions:
          - condition: template
            value_template: "{% if states.light.kitchen_cabinet_lights.attributes.brightness is defined %} {{ states.light.kitchen_cabinet_lights.attributes.brightness < (((0.0625*(states.sun.sun.attributes.elevation**2))-(31.125*states.sun.sun.attributes.elevation)+246.5)|int)}} {% else %} False {% endif %} "
          - condition: template
            value_template: "{{ states.light.kitchen_cabinet_lights.attributes.brightness==null }} "
  action:
    - service: light.turn_on
      entity_id: light.kitchen_cabinet_lights
      data_template:
        brightness: "{{((0.0625*(states.sun.sun.attributes.elevation**2))-(31.125*states.sun.sun.attributes.elevation)+246.5)|int}}"

##########################################################
## Interior - Media accent, cactus light, and master
##########################################################

- alias: "light sunset other lights"
  trigger:
    - platform: state
      entity_id: light.kitchen_cabinet_lights
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "15:00:00"
        before: "21:00:00"
      - condition: numeric_state
        entity_id: sensor.sun_elevation
        above: 0
        below: 9
  action:
    - service: light.turn_on
      entity_id: light.media_accents
    - service: switch.turn_on
      entity_id: switch.cactus
    - service: light.turn_on
      entity_id: light.master_bedroom_lamp
      data:
        kelvin: 6000
        brightness: 150

##########################################################
## Interior - Master lamp switch color when TV on
##########################################################

- alias: "light master tv color switch"
  trigger:
    - platform: state
      entity_id: sensor.master_remote
      from: "PowerOff"
  condition:
    - condition: time
      after: "17:00:00"
      before: "23:00:00"
  action:
    - service: light.turn_on
      entity_id: light.master_bedroom_lamp
      data:
        kelvin: 6000
        brightness: 5

##########################################################
## Interior - Turn off downstairs lights if no motion
##########################################################

- alias: "light turn off kitchen cabinets if no motion after 830pm"
  trigger:
    - platform: time_pattern
      minutes: "/2"
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: time
        after: "20:30:00"
        before: "05:00:00"
      - condition: state
        entity_id: sensor.dark_outside
        state: "True"
      - condition: state
        entity_id: binary_sensor.living_occupancy_on
        state: "off"
      - condition: state
        entity_id: binary_sensor.chalkboard_occupancy_on
        state: "off"
      # - condition: state
      #   entity_id: binary_sensor.back_occupancy_on
      #   state: "off"
      - condition: state
        entity_id: input_boolean.disable_interior_off_830pm
        state: "off"
      - condition: state
        entity_id: remote.media_center
        state: "off"
      - condition: state
        entity_id: group.household
        state: "home"
  action:
    - service: light.turn_on
      entity_id: light.kitchen_cabinet_lights
      data_template:
        brightness: "1"
    - service: light.turn_off
      entity_id: light.media_accents
    - service: switch.turn_off
      entity_id: switch.cactus
    - service: light.turn_off
      entity_id: light.kitchen_cabinet_lights
    # light turning off sometimes triggers motion sensor
    - delay: 0:15
    - service: input_boolean.turn_off
      entity_id: input_boolean.chalkboard_occupancy
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_occupancy

##########################################################
## Interior - Turn on cabinet lights if motion detected
##########################################################

- alias: "turn on kitchen cabinets if motion"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_occupancy_on
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: state # it's dark outside
        entity_id: sensor.dark_outside
        state: "True"
      - condition: template # the lights aren't already on
        value_template: "{{ states.light.kitchen_cabinet_lights.attributes.brightness==null }} "
      - condition: state # someone hasn't disabled the interior motion feature
        entity_id: input_boolean.disable_interior_on_motion
        state: "off"
  action:
    - service: light.turn_on
      entity_id: light.kitchen_cabinet_lights
      data_template:
        brightness: "63"

##########################################################
## Interior - Turn off cabinet lights at sunrise if they are still on
##########################################################

- alias: "turn off kitchen cabinets after sunrise"
  trigger:
    - platform: state
      entity_id: sensor.dark_outside
      to: "False"
  condition:
    - condition: template
      value_template: "{{ states.light.kitchen_cabinet_lights.attributes.brightness!=null }} " # light is on
      # - condition: template
      #   value_template: "{{ states.sensor.illumination_REDACTED.state | int > 12 }} " # lux is greater than 12
  action:
    - service: light.turn_off
      entity_id: light.kitchen_cabinet_lights

##########################################################
## Interior Chalkboard Room
##########################################################

- alias: lights chalkboard room cactus light button
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b76826
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b76826
        click_type: double
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b76826
        click_type: long_click_press
  action:
    - service: switch.toggle
      entity_id: switch.cactus

##########################################################
## Exterior
##########################################################

- alias: lights exterior lights on 5min before sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
  action:
    # Porch and side entrance lights
    - service: light.turn_on
      entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level
      data:
        brightness: 254
    - service: light.turn_on
      entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level_2
      data:
        brightness: 254
    # Front/back 12v landscape lights
    - service: switch.turn_on
      entity_id: switch.outdoor_plug_1
    # Other Landscape lights
    - service: light.turn_on
      entity_id: light.outdoor_string
    - service: light.turn_on
      entity_id: light.smart_flood_lights
    # Spa and Pool light
    - service: light.turn_on
      entity_id: light.lights
 
- alias: lights exterior lights dim at 9pm
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_dim_9pm
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level
      data:
        transition: 60
        brightness_pct: 15
    - service: light.turn_on
      entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level_2
      data:
        transition: 60
        brightness_pct: 15

- alias: exterior lights off if no motion after 11pm
  trigger:
    - platform: time_pattern
      minutes: "/30"
      seconds: 00
  condition:
    - condition: time
      after: "23:00:00"
      before: "05:00:00"
    - condition: state
      entity_id: binary_sensor.living_occupancy_on
      state: "off"
    - condition: state
      entity_id: binary_sensor.chalkboard_occupancy_on
      state: "off"
    - condition: state
      entity_id: binary_sensor.back_occupancy_on
      state: "off"
    - condition: state
      entity_id: remote.media_center
      state: "off"
  action:
    # - service: light.turn_off
    #   entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level
    #   data:
    #     transition: 60
    # - service: light.turn_off
    #   entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level_2
    #   data:
    #     transition: 60
    # - service: switch.turn_off
    #   entity_id: switch.outdoor_plug_1
    - service: light.turn_off
      entity_id: light.lights
    - service: light.turn_off
      entity_id: light.outdoor_string
    - service: light.turn_off
      entity_id: light.smart_flood_lights

- alias: lights exterior lights off 30min after sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_off_sunrise
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level
      data:
        transition: 60
    - service: light.turn_off
      entity_id: light.jasco_products_14294_in_wall_smart_dimmer_level_2
      data:
        transition: 60
    - service: switch.turn_off
      entity_id: switch.outdoor_plug_1
    - service: light.turn_off
      entity_id: light.lights
    - service: light.turn_off
      entity_id: light.outdoor_string
    - service: light.turn_off
      entity_id: light.smart_flood_lights
