#################################################################
## Lighting Automations
#################################################################

##########################################################
## Interior - Kitchen Cabinets
##########################################################

- alias: "light sunset transition kitchen cabinets"
  trigger:
    # - platform: state
    #   entity_id: sensor.dark_outside
    #   to: "True"
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_interior_on_sunset
        state: "off"
      - condition: state
        entity_id: light.kitchen_cabinet_lights
        state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_cabinet_lights
        brightness: 5
    - repeat:
        until:
          condition: or
          conditions:
            - condition: template
              value_template: "{{ state_attr('light.kitchen_cabinet_lights', 'brightness') | int(0) >= 254 }}"
            - condition: state
              entity_id: light.kitchen_cabinet_lights
              state: "off"
        sequence:
        - service: light.turn_on
          data:
            entity_id: light.kitchen_cabinet_lights
            brightness: "{{ state_attr('light.kitchen_cabinet_lights', 'brightness') | int(0) + 1 }}"
        - delay:
            seconds: 10

##########################################################
## Interior - media accents
##########################################################

- alias: "light sunset media accents"
  trigger:
    # - platform: state
    #   entity_id: sensor.dark_outside
    #   to: "True"
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_interior_on_sunset
        state: "off"
      - condition: state
        entity_id: light.media_accents
        state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.media_accents
        brightness: 80
        kelvin: 4500
    # - repeat:
    #     until:
    #       condition: or
    #       conditions:
    #         - condition: template
    #           value_template: "{{ state_attr('light.media_accents', 'brightness') | int(0) >= 100 }}"
    #         - condition: state
    #           entity_id: light.media_accents
    #           state: "off"
    #     sequence:
    #     - service: light.turn_on
    #       data:
    #         entity_id: light.media_accents
    #         brightness: "{{ state_attr('light.media_accents', 'brightness') | int(0) + 1 }}"
    #     - delay:
    #         seconds: 30

##########################################################
## Interior - media center lamp bulbs
##########################################################

- alias: "light sunset media center lamp bulbs"
  trigger:
    # - platform: state
    #   entity_id: sensor.dark_outside
    #   to: "True"
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_interior_on_sunset
        state: "off"
      - condition: state
        entity_id: light.media_center_lamp_bulbs
        state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.media_center_lamp_bulbs
        brightness: 30
        kelvin: 4500
    # - repeat:
    #     until:
    #       condition: or
    #       conditions:
    #         - condition: template
    #           value_template: "{{ state_attr('light.media_center_lamp_bulbs', 'brightness') | int(0) >= 80 }}"
    #         - condition: state
    #           entity_id: light.media_center_lamp_bulbs
    #           state: "off"
    #     sequence:
    #     - service: light.turn_on
    #       data:
    #         entity_id: light.media_center_lamp_bulbs
    #         brightness: "{{ state_attr('light.media_center_lamp_bulbs', 'brightness') | int(0) + 1 }}"
    #     - delay:
    #         seconds: 30

##########################################################
## Interior - main bedroom
##########################################################

- alias: "light sunset main bedroom"
  trigger:
    # - platform: state
    #   entity_id: sensor.dark_outside
    #   to: "True"
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_interior_on_sunset
        state: "off"
      - condition: state
        entity_id: light.master_bedroom_lamp
        state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom_lamp
        brightness: 10
        kelvin: 4000
    - repeat:
        until:
          condition: or
          conditions:
            - condition: template
              value_template: "{{ state_attr('light.master_bedroom_lamp', 'brightness') | int(0) >= 127 }}"
            - condition: state
              entity_id: light.master_bedroom_lamp
              state: "off"
        sequence:
        - service: light.turn_on
          data:
            entity_id: light.master_bedroom_lamp
            brightness: "{{ state_attr('light.master_bedroom_lamp', 'brightness') | int(0) + 1 }}"
        - delay:
            seconds: 20

##########################################################
## Interior - chalkboard room accents (cactus & neon)
##########################################################

- alias: "light sunset chalkboard room cactus"
  trigger:
    # - platform: state
    #   entity_id: sensor.dark_outside
    #   to: "True"
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_interior_on_sunset
        state: "off"
      - condition: state
        entity_id: switch.cactus
        state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.cactus

- alias: "light sunset chalkboard room neon"
  trigger:
    # - platform: state
    #   entity_id: sensor.dark_outside
    #   to: "True"
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_interior_on_sunset
        state: "off"
      - condition: state
        entity_id: switch.neon
        state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.neon

##########################################################
## Interior - Master lamp switch color when TV on
##########################################################

- alias: "light master tv color switch"
  trigger:
    - platform: state
      entity_id: sensor.master_remote
      from: "PowerOff"
  condition:
    - condition: time
      after: "17:00:00"
      before: "23:00:00"
  action:
    - service: light.turn_on
      entity_id: light.master_bedroom_lamp
      data:
        kelvin: 4000
        brightness_pct: 5

##########################################################
## Interior - Turn off downstairs lights if no motion
##########################################################

- alias: "light turn off kitchen cabinets if no motion after 9pm"
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "21:00:00"
        before: "06:00:00"
      - condition: state
        entity_id: sensor.dark_outside
        state: "True"
      - condition: state
        entity_id: binary_sensor.living_occupancy_on
        state: "off"
      - condition: state
        entity_id: binary_sensor.chalkboard_occupancy_on
        state: "off"
      - condition: state
        entity_id: binary_sensor.back_occupancy_on
        state: "off"
      - condition: state
        entity_id: input_boolean.disable_interior_off_9pm
        state: "off"
      - condition: state
        entity_id: remote.media_center
        state: "off"
      # - condition: state
      #   entity_id: group.household
      #   state: "home"
  action:
    - service: light.turn_on
      entity_id: light.kitchen_cabinet_lights
      data_template:
        brightness: "1"
    - service: light.turn_off
      entity_id: light.media_accents
    - service: switch.turn_off
      entity_id: switch.cactus
    - service: switch.turn_off
      entity_id: switch.neon
    - service: light.turn_off
      entity_id: light.kitchen_cabinet_lights
    - service: light.turn_off
      entity_id: light.media_center_lamp_bulbs
    # light turning off sometimes triggers motion sensor
    - delay: 0:15
    - service: input_boolean.turn_off
      entity_id: input_boolean.chalkboard_occupancy
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_occupancy

##########################################################
## Interior - Turn on cabinet lights if motion detected
##########################################################

- alias: "turn on kitchen cabinets if motion"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_occupancy_on
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: state # it's dark outside
        entity_id: sensor.dark_outside
        state: "True"
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      # - condition: template # the lights aren't already on
      #   value_template: "{{ states.light.kitchen_cabinet_lights.attributes.brightness==null }}"
      - condition: state # someone hasn't disabled the interior motion feature
        entity_id: input_boolean.disable_interior_on_motion
        state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_cabinet_lights
        brightness: 100

##########################################################
## Interior - Turn off cabinet lights at sunrise if they are still on
##########################################################

- alias: "turn off kitchen cabinets after sunrise"
  trigger:
    - platform: state
      entity_id: sensor.dark_outside
      to: "False"
  condition:
    - condition: template
      value_template: "{{ states.light.kitchen_cabinet_lights.attributes.brightness!=null }} " # light is on
      # - condition: template
      #   value_template: "{{ states.sensor.illumination_REDACTED.state | int > 12 }} " # lux is greater than 12
  action:
    - service: light.turn_off
      entity_id: light.kitchen_cabinet_lights

##########################################################
## Interior Chalkboard Room
##########################################################

- alias: lights chalkboard room cactus light button
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:15:8d:00:01:b7:68:26
        unique_id: 00:15:8d:00:01:b7:68:26:1:0x0006
        device_id: b8bd41b37c6bf40b762ce1d424f3552f
  action:
    - service: switch.toggle
      entity_id: switch.cactus
    - service: switch.toggle
      entity_id: switch.neon
