#################################################################
## Doorbell Automations
#################################################################

        ##########################################################
        ## Doorbell
        ##########################################################

- alias: doorbell turn exterior lights to 100 when rung after 10pm
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '22:00:00'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id: light.exterior_porch_lights
      data:
        brightness_pct: 100
        kelvin: 3425
    - service: light.turn_on
      entity_id: light.exterior_flood_lights
      data:
        brightness_pct: 100
        kelvin: 3425
    - service: light.turn_on
      entity_id: light.front_spotlights
      data:
        brightness_pct: 100
        kelvin: 4000

- alias: doorbell reset exterior lights to 15 after ring after 10pm
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        after: '22:00:00'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id: light.exterior_porch_lights
      data:
        brightness_pct: 15
        transition: 60
    - service: light.turn_on
      entity_id: light.exterior_flood_lights
      data:
        brightness_pct: 15
        transition: 60
    - service: light.turn_on
      entity_id: light.front_spotlights
      data:
        brightness_pct: 50

- alias: doorbell turn exterior lights to 100 when motion detected after 10pm
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.side_motion
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '22:00:00'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id: light.exterior_porch_lights
      data:
        brightness_pct: 100
        kelvin: 3425
    - service: light.turn_on
      entity_id: light.exterior_flood_lights
      data:
        brightness_pct: 100
        kelvin: 3425
      entity_id: light.front_spotlights
      data:
        brightness_pct: 100
        kelvin: 4000

- alias: doorbell reset exterior lights to 15 after motion detected after 10pm
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        after: '22:00:00'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id: light.exterior_porch_lights
      data:
        brightness_pct: 15
        transition: 60
    - service: light.turn_on
      entity_id: light.exterior_flood_lights
      data:
        brightness_pct: 15
        transition: 60
    - service: light.turn_on
      entity_id: light.front_spotlights
      data:
        brightness_pct: 50

- alias: side reset exterior lights to 15 after motion detected after 10pm
  trigger:
    - platform: state
      entity_id: binary_sensor.side_motion
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        after: '22:00:00'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id: light.exterior_porch_lights
      data:
        brightness_pct: 15
        transition: 60
    - service: light.turn_on
      entity_id: light.exterior_flood_lights
      data:
        brightness_pct: 15
        transition: 60
    - service: light.turn_on
      entity_id: light.front_spotlights
      data:
        brightness_pct: 50
