#################################################################
## Lighting Automations
#################################################################

        ##########################################################
        ## Exterior
        ##########################################################

        ##########################################################
        ## Interior - Kitchen Cabinets
        ##########################################################

- alias: 'sunset transition kitchen cabinets'
  trigger:
  - platform: time_pattern
    minutes: '/2'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: time
        after: '18:00:00'
        before: '20:30:00'
      - condition: numeric_state
        entity_id: sensor.sun_elevation
        above: 3
        below: 8
      - condition: or
        conditions:
          - condition: template
            value_template: '{% if states.light.kitchen_cabinet_lights.attributes.brightness is defined %} {{ states.light.kitchen_cabinet_lights.attributes.brightness < (((0.0625*(states.sun.sun.attributes.elevation**2))-(31.125*states.sun.sun.attributes.elevation)+246.5)|int)}} {% else %} False {% endif %} '
          - condition: template
            value_template: '{{ states.light.kitchen_cabinet_lights.attributes.brightness==null }} '
  action:
    - service: light.turn_on
      entity_id: light.kitchen_cabinet_lights
      data_template: 
        brightness: '{{((0.0625*(states.sun.sun.attributes.elevation**2))-(31.125*states.sun.sun.attributes.elevation)+246.5)|int}}'
    - service: light.turn_on
      entity_id: light.media_accents
    - service: switch.turn_on
      entity_id: switch.01200697dc4f22020616
        
- alias: 'turn off kitchen cabinets if no motion after 9pm'
  trigger:
  - platform: time_pattern
    minutes: '/2'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00:00'
        before: '01:00:00'
      - condition: state
        entity_id: binary_sensor.living_occupancy_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.chalkboard_occupancy_on
        state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.kitchen_cabinet_lights
    - service: light.turn_off
      entity_id: light.media_accents
    - service: switch.turn_off
      entity_id: switch.01200697dc4f22020616
    # light turning off sometimes triggers motion sensor
    - delay: 0:15
    - service: input_boolean.turn_off
      entity_id: input_boolean.chalkboard_occupancy
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_occupancy
      
- alias: 'turn on kitchen cabinets if motion after 9pm'
  trigger:
  - platform: state
    entity_id: binary_sensor.living_occupancy_on, binary_sensor.chalkboard_occupancy_on
    from: "off"
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00:00'
        before: '23:59:59'
      - condition: template
        value_template: '{{ states.light.kitchen_cabinet_lights.attributes.brightness==null }} '
        #value_template: '{% if states.light.kitchen_cabinet_lights.attributes.brightness is defined %} True {% else %} False {% endif %}'
  action:
    - service: light.turn_on
      entity_id: light.kitchen_cabinet_lights
      data_template: 
        brightness: '127'