#################################################################
## Text Notification Automations
#################################################################

##########################################################
## Pushbullet - Notification Test
##########################################################

- alias: notification text test pushbullet
  trigger:
    - platform: state
      entity_id: input_boolean.test_text_notification_pushbullet
      from: "off"
      to: "on"
  action:
    - service: notify.pushbullet
      data:
        title: "Home Assistant"
        message: "This is a test."
    - service: homeassistant.turn_off
      entity_id:
        input_boolean.test_text_notification_pushbullet

##########################################################
## Slack - Notification Test
##########################################################

- alias: notification text test slack
  trigger:
    - platform: state
      entity_id: input_boolean.test_text_notification_slack
      from: "off"
      to: "on"
  action:
    - service: notify.slack
      data:
        title: "Home Assistant"
        message: "This is a test."
    - service: homeassistant.turn_off
      entity_id:
        input_boolean.test_text_notification_slack
        
##########################################################
## Pushbullet - Life360 Overdue Update
##########################################################

- alias: notification life360 overdue update
  trigger:
    - platform: event
      event_type: life360_update_overdue
  action:
    - service: notify.slack
      data:
        title: "Home Assistant"
        message: >
          Update for {{
            state_attr(trigger.event.data.entity_id, 'friendly_name') or
            trigger.event.data.entity_id
          }} is overdue.

- alias: notification life360 update restored
  trigger:
    platform: event
    event_type: life360_update_restored
  action:
    - service: notify.slack
      data:
        title: "Home Assistant"
        message: >
          Update for {{
            state_attr(trigger.event.data.entity_id, 'friendly_name') or
            trigger.event.data.entity_id
          }} restored after {{ trigger.event.data.wait }}.

        ##########################################################
        ## AirVisual - Pollution Level Change
        ##########################################################

- alias: notification airvisual pollution level change
  trigger:
    - platform: state
      entity_id: sensor.u_s_air_pollution_level
      to: "Good"
    - platform: state
      entity_id: sensor.u_s_air_pollution_level
      to: "Moderate"
    - platform: state
      entity_id: sensor.u_s_air_pollution_level
      to: "Unhealthy for Sensitive Groups"
    - platform: state
      entity_id: sensor.u_s_air_pollution_level
      to: "Unhealthy"
    - platform: state
      entity_id: sensor.u_s_air_pollution_level
      to: "Very unhealthy"
    - platform: state
      entity_id: sensor.u_s_air_pollution_level
      to: "Hazardous"
  action:
    - service: notify.pushbullet
      data:
        title: "Home Assistant"
        message: "AirVisual pollution level has change to {{ states.sensor.u_s_air_pollution_level.state }}! The new Air Quality Index (AQI) is {{ states.sensor.u_s_air_quality_index.state }}. The main pollutant is {{ states.sensor.u_s_main_pollutant.state }}."
