#################################################################
## Audio Notification Automations
#################################################################

##########################################################
## Sonos - Notification Test
##########################################################

- alias: notification audio test
  trigger:
    - platform: state
      entity_id: input_boolean.test_audio_notification
      from: 'off'
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft, media_player.office'
          volume: '.6'
          what: >
            {% set hour = now().strftime("%H") %}
            {% set weekday_full_name = now().strftime("%A") %}
            {% set month_full_name = now().strftime("%B") %}
            {% set day = now().strftime("%-d") %}
            {% set weekday = now().strftime("%w") %}
            {% if hour | int < 12 %}
            Good morning.
            {% elif hour | int < 18 %}
            Good afternoon.
            {% else %}
            Good evening.
            {% endif %}
            This is a test of the text to speech engine.
            Today is {{ weekday_full_name }} {{ month_full_name }} the
              {% if day | int == 1 or day | int == 21 or day | int == 31 %}
                {{ day }}st
              {% elif day | int == 2 or day | int == 22 %}
                {{ day }}nd
              {% elif day | int == 3 or day | int == 23 %}
                {{ day }}rd
              {% else %}
                {{ day }}th
              {% endif %}.
            AirVisual pollution level is {{ states.sensor.u_s_air_pollution_level.state }}! The Air Quality Index (AQI) is {{ states.sensor.u_s_air_quality_index.state }} and the main pollutant is {{ states.sensor.u_s_main_pollutant.state }}.
            End of text to speech test.
    - delay: '00:00:01'
    - service: homeassistant.turn_off
      entity_id: input_boolean.test_audio_notification

##########################################################
## Sonos - Garage door has been open for 30min
##########################################################

- alias: notification audio garage open for 30min
  trigger:
    - platform: state
      entity_id: binary_sensor.ecolink_garage_door_tilt_sensor_sensor
      to: 'on'
      for:
        minutes: 30
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '07:00'
      before: '21:00'
    - condition: state
      entity_id: binary_sensor.garage_occupancy_on
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: state
      entity_id: input_boolean.house_cleaning_mode
      state: 'off'
  action:
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft, media_player.office'
          volume: '.6'
          what: 'The garage has been open for 30 minutes.'

##########################################################
## Sonos - Notification REDACTED First Bell
##########################################################

- alias: notification school first bell
  trigger:
    - platform: time
      at: "8:05:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
      - condition: state
        entity_id: input_boolean.disable_notification_school
        state: "off"
  action:
    - service: script.turn_on
      entity_id: script.school_say
      data_template:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft, media_player.office'
          volume: '.6'
          what: >
            First bell, school starts in 10 minutes. 

##########################################################
## Sonos - Notification REDACTED Second Bell
##########################################################

- alias: notification school second bell
  trigger:
    - platform: time
      at: "8:15:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
      - condition: state
        entity_id: input_boolean.disable_notification_school
        state: "off"
  action:
    - service: script.turn_on
      entity_id: script.school_say
      data_template:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft, media_player.office'
          volume: '.6'
          what: >
            Have a great day at school. 

##########################################################
## Sonos - usertwo has arrived at work
##########################################################

- alias: notification audio usertwo arrived at work
  trigger:
    - platform: state
      entity_id: device_tracker.life360_REDACTED_REDACTED
      to: 'Work'
  condition:
    - condition: state
      entity_id: device_tracker.life360_userone_REDACTED
      state: 'home'
    - condition: time
      after: '07:00'
      before: '09:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft, media_player.office'
          volume: '.6'
          what: 'usertwo has arrived at work.'

##########################################################
## Sonos - usertwo Left Work
##########################################################

- alias: notification audio usertwo left work
  trigger:
    - platform: state
      entity_id: device_tracker.life360_REDACTED_REDACTED
      from: 'Work'
      to: 'Away'
    - platform: state
      entity_id: device_tracker.life360_REDACTED_REDACTED
      from: 'Work'
      to: 'moving'
    - platform: state
      entity_id: device_tracker.life360_REDACTED_REDACTED
      from: 'Work'
      to: 'driving'
  condition:
    - condition: state
      entity_id: device_tracker.life360_userone_REDACTED
      state: 'home'
    - condition: time
      after: '14:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:10'
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft, media_player.office'
          volume: '.6'
          what: "usertwo has left work and will arrive home in about {{states('sensor.usertwo_to_home')}} minutes."
            