#################################################################
## Occupancy Automations
#################################################################

#################################################################
## Living Room Occupancy
#################################################################

- alias: occupancy living turn on if motion detected
  trigger:
    # - platform: state
    #   #tapo motion
    #   entity_id: binary_sensor.living_motion
    #   from: "off"
    #   to: "on"
    # - platform: state
    #   #frigate motion
    #   entity_id: binary_sensor.living_motion_2
    #   from: "off"
    #   to: "on"
    - platform: state
      #aqara motion sensor
      entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone_2
      from: "off"
      to: "on"
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.living_person_occupancy
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.living_occupancy

#################################################################
## Reset Living Room Occupancy
#################################################################

- alias: occupancy living turn off after 10min of no motion
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.living_motion
      to: "off"
      for:
        minutes: 10
    - platform: state
      #frigate motion
      entity_id: binary_sensor.living_motion_2
      to: "off"
      for:
        minutes: 10
    - platform: state
      #aqara motion sensor
      entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone_2
      to: "off"
      for:
        minutes: 10
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.living_person_occupancy
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_occupancy

#################################################################
## Back Occupancy
#################################################################

- alias: occupancy back turn on if motion detected
  trigger:
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.back_person_occupancy
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.back_occupancy

#################################################################
## Reset Back Occupancy
#################################################################

- alias: occupancy back turn off after 10min of no motion
  trigger:
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.back_person_occupancy
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.back_occupancy

- alias: occupancy back turn off if unavailable
  trigger:
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.back_person_occupancy
      to: "unavailable"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.back_occupancy

#################################################################
## Front Occupancy
#################################################################

- alias: occupancy front turn on if motion detected
  trigger:
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.front_person_occupancy
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.front_occupancy

#################################################################
## Reset Front Occupancy
#################################################################

- alias: occupancy front turn off after 10min of no motion
  trigger:
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.front_person_occupancy
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.front_occupancy

- alias: occupancy front turn off if unavailable
  trigger:
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.front_person_occupancy
      to: "unavailable"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.front_occupancy

#################################################################
## Garage Occupancy
#################################################################

- alias: occupancy garage turn on if motion detected
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.garage_motion
      from: "off"
      to: "on"
    - platform: state
      #frigate motion
      entity_id: binary_sensor.garage_motion_2
      from: "off"
      to: "on"
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.garage_person_occupancy
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.garage_occupancy

#################################################################
## Reset Garage Occupancy
#################################################################

- alias: occupancy garage turn off after 10min of no motion
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.garage_motion
      to: "off"
      for:
        minutes: 10
    - platform: state
      #frigate motion
      entity_id: binary_sensor.garage_motion_2
      to: "off"
      for:
        minutes: 10
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.garage_person_occupancy
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.garage_occupancy

- alias: occupancy garage turn off if unavailable
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.garage_motion
      to: "unavailable"
    - platform: state
      #frigate motion
      entity_id: binary_sensor.garage_motion_2
      to: "unavailable"
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.garage_person_occupancy
      to: "unavailable"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.garage_occupancy

#################################################################
## Chalkboard Room Occupancy
#################################################################

- alias: occupancy chalkboard turn on if motion detected
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.chalkboard_motion
      from: "off"
      to: "on"
    - platform: state
      #frigate motion
      entity_id: binary_sensor.chalkboard_motion_2
      from: "off"
      to: "on"
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.chalkboard_person_occupancy
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.chalkboard_occupancy

#################################################################
## Reset Chalkboard Room Occupancy
#################################################################

- alias: occupancy chalkboard turn off after 10min of no motion
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.chalkboard_motion
      to: "off"
      for:
        minutes: 10
    - platform: state
      #frigate motion
      entity_id: binary_sensor.chalkboard_motion_2
      to: "off"
      for:
        minutes: 10
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.chalkboard_person_occupancy
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.chalkboard_occupancy

- alias: occupancy chalkboard turn off if unavailable
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.chalkboard_motion
      to: "unavailable"
    - platform: state
      #frigate motion
      entity_id: binary_sensor.chalkboard_motion_2
      to: "unavailable"
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.chalkboard_person_occupancy
      to: "unavailable"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.chalkboard_occupancy

#################################################################
## Shop Occupancy
#################################################################

- alias: occupancy shop turn on if motion detected
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.shop_motion
      from: "off"
      to: "on"
    - platform: state
      #frigate motion
      entity_id: binary_sensor.shop_motion_2
      from: "off"
      to: "on"
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.shop_person_occupancy
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.shop_occupancy

#################################################################
## Reset Shop Occupancy
#################################################################

- alias: occupancy shop turn off after 10min of no motion
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.shop_motion
      to: "off"
      for:
        minutes: 10
    - platform: state
      #frigate motion
      entity_id: binary_sensor.shop_motion_2
      to: "off"
      for:
        minutes: 10
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.shop_person_occupancy
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.shop_occupancy

- alias: occupancy shop turn off if unavailable
  trigger:
    - platform: state
      #tapo motion
      entity_id: binary_sensor.shop_motion
      to: "unavailable"
    - platform: state
      #frigate motion
      entity_id: binary_sensor.shop_motion_2
      to: "unavailable"
    - platform: state
      #frigate person detection
      entity_id: binary_sensor.shop_person_occupancy
      to: "unavailable"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.shop_occupancy

#################################################################
## Office Occupancy
#################################################################

- alias: occupancy office turn on if motion detected
  trigger:
    - platform: state
      #aqara motion sensor
      entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.office_occupancy

#################################################################
## Reset Office Occupancy
#################################################################

- alias: occupancy office turn off after 10min of no motion
  trigger:
    - platform: state
      #aqara motion sensor
      entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id:
        input_boolean.office_occupancy

##########################################################
## WFH Mode
##########################################################

- alias: occupancy wfh home on
  trigger:
    - platform: time
      at: "06:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.wfh_mode

- alias: occupancy wfh off
  trigger:
    - platform: time
      at: "15:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.wfh_mode

#################################################################
## Vacation Mode Automations
#################################################################

        ##########################################################
        ## Turn on Vacation Mode when Gone 24 Hours
        ##########################################################

- alias: vacation turn on when gone 24 hours
  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 24
        minutes: 0
        seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

##########################################################
## Turn off Vacation Mode when Home
##########################################################

- alias: vacation turn off when home
  trigger:
    - platform: state
      entity_id: group.household
#      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode

#################################################################
## Testing Frigate: https://github.com/blakeblackshear/frigate
#################################################################

- alias: Frigate interior detection mode on
  trigger:
    - platform: state
      entity_id: input_boolean.interior_camera_detection_mode
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.chalkboard_detect
    - service: switch.turn_on
      entity_id: switch.living_detect
    - service: switch.turn_on
      entity_id: switch.shop_detect
    - service: switch.turn_on
      entity_id: switch.garage_detect

- alias: Frigate interior detection mode off
  trigger:
    - platform: state
      entity_id: input_boolean.interior_camera_detection_mode
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.chalkboard_detect
    - service: switch.turn_off
      entity_id: switch.living_detect
    - service: switch.turn_off
      entity_id: switch.shop_detect
    - service: switch.turn_off
      entity_id: switch.garage_detect

- alias: Frigate interior recording mode on
  trigger:
    - platform: state
      entity_id: input_boolean.interior_camera_recording_mode
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.chalkboard_recordings
    - service: switch.turn_on
      entity_id: switch.living_recordings
    - service: switch.turn_on
      entity_id: switch.shop_recordings
    - service: switch.turn_on
      entity_id: switch.garage_recordings

- alias: Frigate interior recording mode off
  trigger:
    - platform: state
      entity_id: input_boolean.interior_camera_recording_mode
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.chalkboard_recordings
    - service: switch.turn_off
      entity_id: switch.living_recordings
    - service: switch.turn_off
      entity_id: switch.shop_recordings
    - service: switch.turn_off
      entity_id: switch.garage_recordings

        ##########################################################
        ## If home turn off detections on interior cameras
        ##########################################################

- alias: Frigate interior detection off when home
  trigger:
    - platform: state
      entity_id: group.household
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.disable_interior_camera_detection
      state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.interior_camera_detection_mode

        ##########################################################
        ## If not home turn on detections on interior cameras
        ##########################################################

- alias: Frigate interior detection on when not_home
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.disable_interior_camera_detection
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.interior_camera_detection_mode

        ##########################################################
        ## If home turn off recording on interior cameras
        ##########################################################

- alias: Frigate interior recording off when home
  trigger:
    - platform: state
      entity_id: group.household
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.disable_interior_camera_recording
      state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.interior_camera_recording_mode

        ##########################################################
        ## If not home turn on recording on interior cameras
        ##########################################################

- alias: Frigate interior recording on when not_home
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.disable_interior_camera_recording
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.interior_camera_recording_mode

        ##########################################################
        ## increase work counter
        ##########################################################

- alias: work counter
  trigger:
    - platform: state
      entity_id: person.userone
      to: 'Work'
      for:
        minutes: 5
  action:
    - service: counter.increment
      target:
        entity_id: counter.userone_work

- alias: reset work counter
  trigger:
    - platform: time
      at: "23:59:59"
  condition:
    - condition: time
      weekday:
        - sun
  action:
    service: counter.reset
    target:
      entity_id: counter.userone_work
