#################################################################
## Occupancy Automations
#################################################################

#################################################################
## Living Room Occupancy
#################################################################

- alias: occupancy living turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_detected
      from: "off"
      to: "on"
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00045eb488
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.living_occupancy

#################################################################
## Reset Living Room Occupancy
#################################################################

- alias: occupancy living turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_detected
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_occupancy

#################################################################
## Garage Occupancy
#################################################################

- alias: occupancy garage turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion_detected
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.garage_occupancy

#################################################################
## Reset Garage Occupancy
#################################################################

- alias: occupancy garage turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion_detected
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.garage_occupancy

#################################################################
## Chalkboard Room Occupancy
#################################################################

- alias: occupancy chalkboard turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.chalkboard_room_motion_detected
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.chalkboard_occupancy

#################################################################
## Reset Chalkboard Room Occupancy
#################################################################

- alias: occupancy chalkboard turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.chalkboard_room_motion_detected
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.chalkboard_occupancy

#################################################################
## Shop Occupancy
#################################################################

- alias: occupancy shop turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.shop_motion_detected
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.shop_occupancy

#################################################################
## Reset Shop Occupancy
#################################################################

- alias: occupancy shop turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.shop_motion_detected
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.shop_occupancy

#################################################################
## Office Occupancy
#################################################################

- alias: occupancy office turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00047eaffc
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.office_occupancy

#################################################################
## Reset Office Occupancy
#################################################################

- alias: occupancy office turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00047eaffc
      to: "off"
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id:
        input_boolean.office_occupancy

##########################################################
## WFH Mode
##########################################################

- alias: occupancy wfh home on
  trigger:
    - platform: time
      at: "06:30:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.wfh_mode

- alias: occupancy wfh off
  trigger:
    - platform: time
      at: "16:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.wfh_mode

#################################################################
## Vacation Mode Automations
#################################################################

        ##########################################################
        ## Turn on Vacation Mode when Gone 24 Hours
        ##########################################################

- alias: vacation turn on when gone 24 hours
  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 24
        minutes: 0
        seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

##########################################################
## Turn off Vacation Mode when Home
##########################################################

- alias: vacation turn off when home
  trigger:
    - platform: state
      entity_id: group.household
#      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode
