#################################################################
## Occupancy Automations
#################################################################

      #################################################################
      ## Living Room Occupancy
      #################################################################

- alias: occupancy living turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_detected
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.living_occupancy

      #################################################################
      ## Reset Living Room Occupancy
      #################################################################

- alias: occupancy living turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_detected
      to: 'off'
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_occupancy

      #################################################################
      ## Garage Occupancy
      #################################################################

- alias: occupancy garage turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion_detected
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.garage_occupancy

      #################################################################
      ## Reset Garage Occupancy
      #################################################################

- alias: occupancy garage turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion_detected
      to: 'off'
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.garage_occupancy

      #################################################################
      ## Chalkboard Room Occupancy
      #################################################################

- alias: occupancy chalkboard turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.chalkboard_room_motion_detected
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.chalkboard_occupancy

      #################################################################
      ## Reset Chalkboard Room Occupancy
      #################################################################

- alias: occupancy chalkboard turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.chalkboard_room_motion_detected
      to: 'off'
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.chalkboard_occupancy

      #################################################################
      ## Shop Occupancy
      #################################################################

- alias: occupancy shop turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.shop_motion_detected
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.shop_occupancy

      #################################################################
      ## Reset Shop Occupancy
      #################################################################

- alias: occupancy shop turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.shop_motion_detected
      to: 'off'
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.shop_occupancy
      
      #################################################################
      ## Baby Occupancy
      #################################################################

- alias: occupancy baby turn on if motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.synosurveillance_motion
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.baby_occupancy

      #################################################################
      ## Reset Baby Occupancy
      #################################################################

- alias: occupancy baby turn off after 10min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.synosurveillance_motion
      to: 'off'
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.baby_occupancy