#################################################################
## turn off the office air purifier
#################################################################

- alias: turn off office air purifier 
  trigger:
    - platform: numeric_state
      entity_id: sensor.ikea_air_quality_2_vindriktning_pm2_5
      value_template: "{{ states('sensor.ikea_air_quality_2_vindriktning_pm2_5') | int }}"
      below: 6
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: fan.office_air_purifier
      state: "on"
    - condition: state
      entity_id: input_boolean.office_occupancy
      state: "off"
    - condition: state
      entity_id: input_boolean.disable_auto_purifier_mode
      state: "off"
  action:
    service: fan.turn_off
    entity_id: fan.office_air_purifier

#################################################################
## every 15 minutes change purifier mode based on air quality
#################################################################

- alias: office air purifier based on air quality
  trigger:
    - platform: time_pattern
      minutes: "/15"
      seconds: 00
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: fan.office_air_purifier
      state: "on"
    - condition: state
      entity_id: input_boolean.disable_auto_purifier_mode
      state: "off"
  action:
  - service: fan.set_preset_mode
    target:
      entity_id: fan.office_air_purifier
    data_template:
      preset_mode: >
        {% set pm2_5 = states('sensor.ikea_air_quality_2_vindriktning_pm2_5') | float %}
        {% if 5 < pm2_5 < 35 %}
          Low
        {% elif 36 < pm2_5 < 85 %}
          Medium
        {% elif 86 < pm2_5 %}
          High
        {% else %}
          Sleep
        {% endif %}

#################################################################
## Turn on office purifier if office is occupied
#################################################################

- alias: climate office purifier on when occupied
  trigger:
    - platform: state
      entity_id: input_boolean.office_occupancy
      to: "on"
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: fan.office_air_purifier
      state: "off"
    - condition: state
      entity_id: input_boolean.disable_auto_purifier_mode
      state: "off"
  action:
    - service: fan.turn_on
      entity_id: fan.office_air_purifier
