##########################################################
## Sleep Time
##########################################################

- alias: sleeptime
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_time
      to: "on"
      for:
        hours: 0
        minutes: 1
        seconds: 0
  action:
    - delay: "00:30:00"
    - service: script.turn_on
      data:
        entity_id: script.master_harmony_off

- alias: sleeptime reset
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_time
      to: "on"
      for:
        hours: 0
        minutes: 31
        seconds: 0
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sleep_time

- alias: media master remote sleep time
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:15:8d:00:01:b8:6a:74
        unique_id: 00:15:8d:00:01:b8:6a:74:1:0x0006
        device_id: c20325cb807c12a207909d6b2110460f
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:15:8d:00:04:50:d5:82
        unique_id: 00:15:8d:00:04:50:d5:82:1:0x0012
        device_id: 27bd5c7991ffa64d0dfbe9619884d158
    - platform: state
      entity_id: input_button.sleeptime
  action:
    - service: homeassistant.toggle
      entity_id: input_boolean.sleep_time
    - service: remote.send_command
      data_template:
        entity_id: remote.master
        command: "VolumeUp"
        device: 79346609
    - service: light.turn_off
      entity_id: light.master_bedroom_lamp
    - service: light.turn_off
      entity_id: light.loft_lamp_bulb
    - service: fan.set_preset_mode
      target:
        entity_id: fan.office_air_purifier
      data:
        preset_mode: Sleep
