#################################################################
## Sprinkler
#################################################################

        ##########################################################
        ## Sprinkler - Spring (Mon, Wed, Fri, & Sat - AM) 1.5 hrs total
        ##########################################################

- alias: 'water spring'
  trigger:
  - platform: time
    at: "05:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
          - sat
      - condition: state
        entity_id: input_select.sprinkler
        state: 'Spring'
  action:
    - service: script.sprinkler_water_spring

        ##########################################################
        ## Sprinkler - Winter (Mon, Wed, Fri, - AM) 1 hrs total
        ##########################################################

- alias: 'water winter'
  trigger:
  - platform: time
    at: "05:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
      - condition: state
        entity_id: input_select.sprinkler
        state: 'Winter'
  action:
    - service: script.sprinkler_water_winter

        ##########################################################
        ## Sprinkler - Summer (Mon, Wed, Thur, Sat, & Sun - AM/PM) 3 hrs total
        ##########################################################

- alias: 'water summer'
  trigger:
  - platform: time
    at: "05:00:00"
  - platform: time
    at: "17:00:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - wed
          - thu
          - sat
          - sun
      - condition: state
        entity_id: input_select.sprinkler
        state: 'Summer'
  action:
    - service: script.sprinkler_water_summer
