#################################################################
## System Automations
#################################################################


        ##########################################################
        ## Clean TTS Cache once a week
        ##########################################################

- alias: system clear tts cache
  trigger:
    - platform: time
      at: "23:59:59"
  condition:
    - condition: time
      weekday:
        - mon
  action:
    service: tts.clear_cache

        ##########################################################
        ## New device connected
        ##########################################################

- alias: system new device connected
  trigger:
    - platform: event
      event_type: entity_registry_updated
      event_data:
        action: create
  condition:
    - condition: template
      value_template: "{{trigger.event.data.entity_id.split('.')[0] == 'device_tracker' }}"
  action:
    - variables:
        entity: >
          {{trigger.event.data.entity_id}}
    - service: notify.ntalekt
      data_template:
        message: >
          New device registered: {{state_attr(entity,'friendly_name')}}
          Entity: {{entity}}
          Host: {{state_attr(entity,'host_name')}}
          Ip: {{state_attr(entity,'ip')}}
          Mac-address: {{state_attr(entity,'mac')}}
          Full data: {{trigger.event.data}}
        title: Home Assistant
        target: "#network"

        ##########################################################
        ## Pi-hole update status
        ##########################################################

- alias: update pi-hole switch because it is slow
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: switch
        service: toggle
        service_data:
          entity_id: switch.pi_hole1
    - platform: event
      event_type: call_service
      event_data:
        domain: switch
        service: toggle
        service_data:
          entity_id: switch.pi_hole2
  action:
    - service: homeassistant.update_entity
      target:
        entity_id:
          - switch.pi_hole1
          - switch.pi_hole2