#################################################################
## System Automations
#################################################################


        ##########################################################
        ## Clean TTS Cache once a week
        ##########################################################

- alias: system clear tts cache
  trigger:
    - platform: time
      at: "23:59:59"
  condition:
    - condition: time
      weekday:
        - mon
  action:
    service: tts.clear_cache

        ##########################################################
        ## New device connected
        ##########################################################

- alias: system new device connected
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: notify.slack
      data_template:
        message: >
          New device:
          {{trigger.event.data.host_name}}
          ({{trigger.event.data.entity_id}})
          Mac: {{trigger.event.data.mac}}
        title: Home Assistant
