##########################################################
## time lapse stuffs
##########################################################

  ##########################################################
  ## install prerequisites
  ##########################################################

- alias: install imagemagick so we can use it to manipulate images
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: shell_command.install_imagemagick

  ##########################################################
  ## check uploads
  ##########################################################

- alias: check we are uploading daily
  trigger:
    - platform: template
      # true if sensor has not updated in 24 hours
      value_template: "{{ now() - states.sensor.REDACTED_channel_videos.last_changed >= timedelta (minutes=1440) }}"
  action:
    - service: notify.homeassistant_dis
      data:
        message: "{{ now().timestamp() | timestamp_local }} Check youtube uploads. No uploads in 24 hours."
        target: ["REDACTED"]

  ##########################################################
  ## f1
  ##########################################################

- alias: turn_on_f1_timelapse
  trigger:
  # turn on timelapse 10min before calendar event
    - platform: template
      value_template: >
        {% if state_attr('calendar.formula_1_calendar_by_racefans_net','start_time') != none %}
          {% set start = state_attr('calendar.formula_1_calendar_by_racefans_net','start_time')|as_datetime|as_local %}
          {{ start - now() < timedelta(minutes=10) }}
        {% endif %}
    # - platform: calendar
    #   event: start
    #   entity_id: calendar.formula_1_calendar_by_racefans_net
  action:
    - service: homeassistant.turn_on
      entity_id:
        # - automation.f1_timelapse_carlossainz
        # - automation.f1_timelapse_charlesleclerc
        # - automation.f1_timelapse_fernandoalonso
        - automation.f1_timelapse_georgerussell
        # - automation.f1_timelapse_lancestroll
        # - automation.f1_timelapse_landonorris
        - automation.f1_timelapse_lewishamilton
        - automation.f1_timelapse_maxverstappen
        # - automation.f1_timelapse_oscarpiastri
        - automation.f1_timelapse_sergioperez
        # - automation.f1_timelapse_data
        # - automation.f1_timelapse_main
        # - automation.f1_timelapse_tracker
    - service: notify.homeassistant_dis
      data:
        message: 'F1 {{ states("sensor.f1_next_event") }} timelapse started based on calendar!'
        target: ["REDACTED"]

- alias: turn_off_f1_timelapse
  trigger:
    - platform: calendar
      event: end
      entity_id: calendar.formula_1_calendar_by_racefans_net
  action:
  # turn off timelapse 10min after calendar end
    - service: notify.homeassistant_dis
      data:
        message: "F1 timelapse stopping in 10 minutes!"
        target: ["REDACTED"]
    - delay: '00:10:00'
    - service: homeassistant.turn_off
      entity_id:
        - automation.f1_timelapse_carlossainz
        - automation.f1_timelapse_charlesleclerc
        - automation.f1_timelapse_fernandoalonso
        - automation.f1_timelapse_georgerussell
        - automation.f1_timelapse_lancestroll
        - automation.f1_timelapse_landonorris
        - automation.f1_timelapse_lewishamilton
        - automation.f1_timelapse_maxverstappen
        - automation.f1_timelapse_oscarpiastri
        - automation.f1_timelapse_sergioperez
        - automation.f1_timelapse_data
        - automation.f1_timelapse_main
        - automation.f1_timelapse_tracker
    - service: notify.homeassistant_dis
      data:
        message: "F1 timelapse stopped based on calendar!"
        target: ["REDACTED"]

- alias: f1_timelapse_main
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_main

- alias: f1_timelapse_tracker
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_tracker

- alias: f1_timelapse_data
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_data

- alias: f1_timelapse_maxverstappen
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_maxverstappen

- alias: f1_timelapse_sergioperez
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_sergioperez

- alias: f1_timelapse_carlossainz
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_carlossainz

- alias: f1_timelapse_charlesleclerc
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_charlesleclerc

- alias: f1_timelapse_lewishamilton
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_lewishamilton

- alias: f1_timelapse_georgerussell
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_georgerussell

- alias: f1_timelapse_landonorris
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_landonorris

- alias: f1_timelapse_oscarpiastri
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_oscarpiastri

- alias: f1_timelapse_fernandoalonso
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_fernandoalonso

- alias: f1_timelapse_lancestroll
  initial_state: off
  trigger:
    - platform: time_pattern
      seconds: "/12"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.disable_f1_timelapse
        state: "off"
  action:
    - service: shell_command.timelapse_create_f1_lancestroll

  ##########################################################
  ## archive 7+ days old raw snapshots
  ##########################################################

- alias: timelapse_archive
  trigger:
    - platform: time
      at: "05:00:00"
  action:
    service: shell_command.timelapse_archive

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "01:25:00"
  action:
    service: shell_command.timelapse_create_REDACTED
    
- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "01:55:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "03:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "03:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "00:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "00:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt iss
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "18:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "18:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "19:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "19:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "00:15:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "00:55:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt Cornell Cam
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "00:15:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "00:55:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## home cameras
  ##########################################################

- alias: home_camera_capture
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    - service: shell_command.timelapse_back
    - service: shell_command.timelapse_front
    - service: shell_command.timelapse_garage
    - service: shell_command.timelapse_shop
    - service: shell_command.timelapse_nature
    - service: shell_command.timelapse_nature2

- alias: back_camera_create
  trigger:
    - platform: time
      at: "01:00:00"
  action:
    - service: shell_command.timelapse_create_back

- alias: front_camera_create
  trigger:
    - platform: time
      at: "01:10:00"
  action:
    - service: shell_command.timelapse_create_front

- alias: garage_camera_create
  trigger:
    - platform: time
      at: "01:20:00"
  action:
    - service: shell_command.timelapse_create_garage

- alias: shop_camera_create
  trigger:
    - platform: time
      at: "01:30:00"
  action:
    - service: shell_command.timelapse_create_shop

- alias: nature_camera_create
  trigger:
    - platform: time
      at: "01:40:00"
  action:
    - service: shell_command.timelapse_create_nature

- alias: nature2_camera_create
  trigger:
    - platform: time
      at: "01:50:00"
  action:
    - service: shell_command.timelapse_create_nature2
