##########################################################
## time lapse stuffs
##########################################################

  ##########################################################
  ## install prerequisites
  ##########################################################

- alias: install imagemagick so we can use it to manipulate images
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: shell_command.install_imagemagick

  ##########################################################
  ## check uploads
  ##########################################################

- alias: check we are uploading daily
  trigger:
    - platform: template
      # true if sensor has not updated in 24 hours
      value_template: "{{ now() - states.sensor.REDACTED_channel_videos.last_changed >= timedelta (minutes=1440) }}"
  action:
    - service: notify.homeassistant_dis
      data:
        message: "{{ now().timestamp() | timestamp_local }} Check youtube uploads. No uploads in 24 hours."
        target: ["REDACTED"]

  ##########################################################
  ## archive 7+ days old raw snapshots
  ##########################################################

- alias: timelapse_archive
  trigger:
    - platform: time
      at: "05:00:00"
  action:
    service: shell_command.timelapse_archive

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "01:25:00"
  action:
    service: shell_command.timelapse_create_REDACTED
    
- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "01:55:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "03:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "03:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "00:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "00:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt iss
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "18:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "18:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "19:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "19:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

# - alias: REDACTED
#   trigger:
#     - platform: time_pattern
#       minutes: "/1"
#   action:
#     service: shell_command.timelapse_REDACTED

# - alias: REDACTED_create
#   trigger:
#     - platform: time
#       at: "00:15:00"
#   action:
#     service: shell_command.timelapse_create_REDACTED

# - alias: REDACTED_create_yt
#   trigger:
#     - platform: time
#       at: "00:55:00"
#   action:
#     service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt Cornell Cam
  ##########################################################

# - alias: REDACTED
#   trigger:
#     - platform: time_pattern
#       minutes: "/1"
#   action:
#     service: shell_command.timelapse_REDACTED

# - alias: REDACTED_create
#   trigger:
#     - platform: time
#       at: "00:15:00"
#   action:
#     service: shell_command.timelapse_create_REDACTED

# - alias: REDACTED_create_yt
#   trigger:
#     - platform: time
#       at: "00:55:00"
#   action:
#     service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt SpaceX Cape Canaveral Space
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "02:25:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "02:55:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## home cameras
  ##########################################################

- alias: home_camera_capture
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    - service: shell_command.timelapse_back
    - service: shell_command.timelapse_front
    - service: shell_command.timelapse_garage
    - service: shell_command.timelapse_shop
    - service: shell_command.timelapse_nature
    - service: shell_command.timelapse_nature2

- alias: back_camera_create
  trigger:
    - platform: time
      at: "01:00:00"
  action:
    - service: shell_command.timelapse_create_back

- alias: front_camera_create
  trigger:
    - platform: time
      at: "01:10:00"
  action:
    - service: shell_command.timelapse_create_front

- alias: garage_camera_create
  trigger:
    - platform: time
      at: "01:20:00"
  action:
    - service: shell_command.timelapse_create_garage

- alias: shop_camera_create
  trigger:
    - platform: time
      at: "01:30:00"
  action:
    - service: shell_command.timelapse_create_shop

- alias: nature_camera_create
  trigger:
    - platform: time
      at: "01:40:00"
  action:
    - service: shell_command.timelapse_create_nature

- alias: nature2_camera_create
  trigger:
    - platform: time
      at: "01:50:00"
  action:
    - service: shell_command.timelapse_create_nature2
