##########################################################
## time lapse stuffs
##########################################################

  ##########################################################
  ## install prerequisites
  ##########################################################

- alias: install imagemagick so we can use it to manipulate images
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: shell_command.install_imagemagick

  ##########################################################
  ## archive 7+ days old raw snapshots
  ##########################################################

- alias: timelapse_archive
  trigger:
    - platform: time
      at: "05:00:00"
  action:
    service: shell_command.timelapse_archive

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: timelapse_REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: timelapse_REDACTED_create
  trigger:
    - platform: time
      at: "02:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: timelapse_REDACTED_create_yt
  trigger:
    - platform: time
      at: "02:35:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "02:25:00"
  action:
    service: shell_command.timelapse_create_REDACTED
    
- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "02:55:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "03:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "04:15:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "01:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "01:35:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "15:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "15:35:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt iss
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "18:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "18:35:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt
