##########################################################
## time lapse stuffs
##########################################################

  ##########################################################
  ## install prerequisites
  ##########################################################

- alias: install imagemagick so we can use it to manipulate images
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: shell_command.install_imagemagick

  ##########################################################
  ## archive 7+ days old raw snapshots
  ##########################################################

- alias: timelapse_archive
  trigger:
    - platform: time
      at: "05:00:00"
  action:
    service: shell_command.timelapse_archive

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: timelapse_REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: timelapse_REDACTED_create
  trigger:
    - platform: time
      at: "02:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: timelapse_REDACTED_create_yt
  trigger:
    - platform: time
      at: "02:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt nsf_spacecoast
  ##########################################################

- alias: timelapse_nsf_spacecoast
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_nsf_spacecoast

- alias: timelapse_nsf_spacecoast_create
  trigger:
    - platform: time
      at: "01:05:00"
  action:
    service: shell_command.timelapse_create_nsf_spacecoast

- alias: timelapse_nsf_spacecoast_create_yt
  trigger:
    - platform: time
      at: "01:45:00"
  action:
    service: shell_command.timelapse_create_nsf_spacecoast_yt

  ##########################################################
  ## yt nsf_mcgregor
  ##########################################################

- alias: timelapse_nsf_mcgregor
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_nsf_mcgregor

- alias: timelapse_nsf_mcgregor_create
  trigger:
    - platform: time
      at: "04:05:00"
  action:
    service: shell_command.timelapse_create_nsf_mcgregor

- alias: timelapse_nsf_mcgregor_create_yt
  trigger:
    - platform: time
      at: "04:45:00"
  action:
    service: shell_command.timelapse_create_nsf_mcgregor_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "01:25:00"
  action:
    service: shell_command.timelapse_create_REDACTED
    
- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "01:55:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "03:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "03:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "00:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "00:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt REDACTED
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "15:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "15:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt

  ##########################################################
  ## yt iss
  ##########################################################

- alias: REDACTED
  trigger:
    - platform: time_pattern
      minutes: "/1"
  action:
    service: shell_command.timelapse_REDACTED

- alias: REDACTED_create
  trigger:
    - platform: time
      at: "18:05:00"
  action:
    service: shell_command.timelapse_create_REDACTED

- alias: REDACTED_create_yt
  trigger:
    - platform: time
      at: "18:45:00"
  action:
    service: shell_command.timelapse_create_REDACTED_yt
